services:
  evilginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evilginx-lab
    network_mode: host
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file:
      - ../../.env
    volumes:
      - ./runtime:/data
      - ./runtime/logs:/data/logs
      - ./runtime/config:/root/.evilginx
    security_opt:
      - no-new-privileges:true
